#!/usr/bin/python3.6
import sys,os
import numpy as np

route = os.open(sys.argv[1]+".fifo", os.O_RDWR)
for line in sys.stdin:
   line=line.rstrip()
   if len(line)==0: continue
   a,b,c,d = np.array(line.split(" ")).astype(int)
   sys.stderr.write("DEBUG: "+line+"\n")
   sys.stderr.flush()
   if(a==0):
        os._exit(1)
   else:
        os.write(route, bytes("%u %u %u %u\n".encode("utf-8") % (a,b,c,d)))



